### ISSUE TITLE
Draw polygons

### ISSUE THREAD

**Issue by pixnbit** [munkh-altai/flutter_map_arcgis#1]
For example I want to draw: https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Congressional_Districts/FeatureServer/0

From the sample code I tried : "esriGeometryPolygon" and "poloygon" both didn't work

**Comment by munkh-altai** [comment]
@pixnbit tank's for create issues
2 bugs fixed.
You can try it. It is okay

**Comment by pixnbit** [comment]
Verfied, it's fixed. Thanks for your speedy response. I found more bugs though:) Filing it in a new ticket
