### ISSUE TITLE
Marker on Featurelayeroption is flickering

### ISSUE THREAD

**Issue by kelbin15** [munkh-altai/flutter_map_arcgis#11]
Hi,

I dunno how to debug it myself. I understood from the codes that you have set a delay of 200milliseconds to load the markers when moving around the map. 

This means
Move --> stop --> Load marker
Move --> stop --> Load marker

However, if you do the following in quick succession
Move --> stop --> move --> stop --> move --> stop 
before the "point/marker" can load, the point/marker will flicker around to catch up and eventually load at the wrong grid.

Seeking your help on this.

Thanks for the package!

**Comment by munkh-altai** [comment]
Point request caller improved version 2.0.2

**Comment by munkh-altai** [comment]
Version 2.0.3 exceededTransferLimit set to true ArcGIS rest API
