### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by pablojimpas** [munkh-altai/flutter_map_arcgis#15]
Currently It's impossible to use this plugin with a decent user experience.

I don't know where but there's a heavy bottleneck that lags the rendering pipeline, I can't reach more than 2 frames per second on my mobile device.

A quick profiling shows way to many time spent in `_drawCircle`, it seems like the FeatureLayer it's rebuilding things every single frame or doing some heavy computations in the build methods, idk.

I'm not familiar with the codebase but I will suggest looking at the implementation of other plugins and  `flutter_map` itself.

Furthermore here are some resources that can be useful:

- https://docs.flutter.dev/testing/common-errors
- https://docs.flutter.dev/perf/rendering/best-practices
- https://www.youtube.com/watch?v=PKGguGUwSYE
- https://www.youtube.com/watch?v=vVg9It7cOfY
- https://www.youtube.com/watch?v=qax_nOpgz7E
- https://www.youtube.com/watch?v=nq43mP7hjAE

**Comment by yinxh2016** [comment]
添加1个2个图层就很卡，地图点不动，如何优化

**Comment by munkh-altai** [comment]
Version 2.0.3 exceededTransferLimit set to true ArcGIS rest API
