### ISSUE TITLE
How to load tile layer of arcgis map in flutter_map?

### ISSUE THREAD

**Issue by tashi146** [munkh-altai/flutter_map_arcgis#18]
I have tilelayer generated from arcgis. Though I am able to plot point and polygon feature layer I am not able to plot map tile layer. 
   Eg below   

[https://services3.arcgis.com/M4I7lJ9tT48smMav/arcgis/rest/services/banglore_plant/FeatureServer/0](https://services3.arcgis.com/M4I7lJ9tT48smMav/arcgis/rest/services/banglore_plant/FeatureServer/0)   

This is what I have tried:   
```
TileLayerOptions(
      urlTemplate:
      'https://services3.arcgis.com/M4I7lJ9tT48smMav/arcgis/rest/services/banglore_plant/FeatureServer/0',
       )
```   
Can anyone tell me how can I plot tilelayer given link in flutter_map?

**Comment by munkh-altai** [comment]
this package currently support feature layer
