### ISSUE TITLE
onTab callback getting called excessive times.

### ISSUE THREAD

**Issue by pixnbit** [munkh-altai/flutter_map_arcgis#2]
I used "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_States_Generalized/FeatureServer/0" to display US states. The number of callbacks is related to the number of polygons on screen. 1 polygon, 1 callback, and 50 polygons, 50 callbacks. with all other callbacks returning 'null' attributes. Is this expected? I don't think so. For now I'll just filter out the null ones. 

`flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: {FID: 12, STATE_NAME: Kansas, STATE_FIPS: 20, SUB_REGION: West North Central, STATE_ABBR: KS, POPULATION: 2970523, POP_SQMI: 36.1, POP2010: 2853118, POP10_SQMI: 34.7, WHITE: 2391044, BLACK: 167864, AMERI_ES: 28150, ASIAN: 67762, HAWN_PI: 2238, HISPANIC: 300042, OTHER: 110127, MULT_RACE: 85933, MALES: 1415408, FEMALES: 1437710, AGE_UNDER5: 205492, AGE_5_9: 202447, AGE_10_14: 198884, AGE_15_19: 203821, AGE_20_24: 204454, AGE_25_34: 377720, AGE_35_44: 346673, AGE_45_54: 406264, AGE_55_64: 331247, AGE_65_74: 190389, AGE_75_84: 126409, AGE_85_UP: 59318, MED_AGE: 36, MED_AGE_M: 34.7, MED_AGE_F: 37.3, HOUSEHOLDS: 1112096, AVE_HH_SZ: 2.49, HSEHLD_1_M: 140529, HSEHLD_1_F: 168809, MARHH_CHD: 250118, MARHH_NO_C: 318191, MHH_CHILD: 32147, FHH_CHILD: 81709, FAMILIES: 734103, AVE_FAM_SZ: 3.06, HSE_UNITS: 1233215, VACANT: 121119, OWNER_OCC: 753532, RENTER_OCC: 358564, NO_FARMS12: 61773, AVE_SIZE12: 747, CROP_ACR12: 28503265, AVE_SALE12: 298845, SQMI: 82277.97, Shape__Area: 348078970838.738, Shape__Le<…>
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)
flutter: null
flutter: LatLng(latitude:38.882523, longitude:-97.096573)`

**Comment by pixnbit** [comment]
```
      var isInclude = _pointInPolygon(position, polygon.points);
      if (isInclude) {

        widget.options.onTap(polygon.attributes, position);
      } else {
        widget.options.onTap(null, position);
      }
```
Look like it's intentional? I wonder why, reporting other polygons not tapped with null info is not useful.

**Comment by munkh-altai** [comment]
Because  polygon on tap event working from GestureDetector.
if you use GestureDetector in flutter map main map on tap event will disable
