### ISSUE TITLE
Can't use along with flutter_map ^3.0.0

### ISSUE THREAD

**Issue by arsyadnimbly** [munkh-altai/flutter_map_arcgis#22]
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/109497576/195638858-eac0bb17-c15b-4085-8a6a-133225fcfba2.png">

Can you guys update this plugin, please?

**Comment by Harishwarrior** [comment]
@munkh-altai

**Comment by munkh-altai** [comment]
Thank for using this package.
we created new release flutter_map_arcgis 2.0.6. this release compatible with flutter map 6
