### ISSUE TITLE
Flickering of Point Layers

### ISSUE THREAD

**Issue by jasonjflaherty** [munkh-altai/flutter_map_arcgis#23]
Just testing out the feasibility of this plugin for Flutter. I noticed while utilizing a point layer the points seem to flicker in and out on the map. I tried both dynamically loaded images and static icons:

```
return PointOptions(
                            width: 30.0,
                            height: 30.0,
                            builder: Icon(Icons.maps_ugc, size: 32));
```

```
return PointOptions(
                          width: 30.0,
                          height: 30.0,
                          builder: CachedNetworkImage(
                              placeholder: (context, url) =>
                                  const CircularProgressIndicator(),
                              imageUrl: "$_markertype"),
                        );
```

...both do this flickering. Then at certain zoom levels (no consistency I can see) the icons are just gone. 
Any thoughts?

![device-2022-10-17-173751](https://user-images.githubusercontent.com/17888282/196308860-da468257-7094-41f1-9a85-996fd7578b53.gif)

**Comment by kike98gg** [comment]
Hi!! I have the same problem, this issue only occurs with point layers... Have you found any solution?

**Comment by munkh-altai** [comment]
Thank for using this package.
we created new release flutter_map_arcgis 2.0.6. this release compatible with flutter map 6
