### ISSUE TITLE
Incompatible with flutter_map v6

### ISSUE THREAD

**Issue by kike98gg** [munkh-altai/flutter_map_arcgis#27]
After the update of the flutter_map package, the flutter_map_arcgis plugin becomes unusable.

**Comment by kelbin15** [comment]
yea, really need your help to update the package.

In the latest flutter, if dont upgrade the arcgis package, there is an error with podspec for iOS.
If upgrade, there is an error with flutter map and decrepitation of plugin api.

Thanks!

**Comment by munkh-altai** [comment]
Thank for using this package.
we created new release flutter_map_arcgis 2.0.6. this release compatible with flutter map 6
