### ISSUE TITLE
FeatureLayer feature does not work

### ISSUE THREAD

**Issue by AnghelAndrei28** [munkh-altai/flutter_map_arcgis#28]
I try to use feature layer, using the example provided, but I am required 2 other parameters in order to use it and it looks like one of them is a custom data class.

![image](https://github.com/khankhulgun/flutter_map_arcgis/assets/45268599/8a39f62c-7022-4d32-9413-6d2758290c11)

**Comment by munkh-altai** [comment]
Please try our example (https://github.com/khankhulgun/flutter_map_arcgis/blob/master/example/lib/main.dart).
