### ISSUE TITLE
Feature requests: ability to specify different paint PolygonOptions for individual pologons

### ISSUE THREAD

**Issue by pixnbit** [munkh-altai/flutter_map_arcgis#3]
I want to paint each polygon with different colors, I'm thinking about some sort of callback so I can provide different options based on the attributes.

**Comment by munkh-altai** [comment]
it is not issue.
We will work unique render feature

**Comment by pixnbit** [comment]
Sounds good! I actually forked your project and added my own logic for this. It's pretty easy to change.
