### ISSUE TITLE
Limit feature in Flutter Map Arcgis and  ServiceFeatureTable is not supported.

### ISSUE THREAD

**Issue by akkamboj** [munkh-altai/flutter_map_arcgis#9]
Hello Flutter Team, We found that there is already flutter plugin provided for the Arcgis Map but with limited feature and  functionality. 
In our application we need to ServiceFeatureTable and FeatureLayer but right now not available in Arcgis map plugin.  If you have any plan to update the arcgis pulgin, when we can expect the update.

**Comment by munkh-altai** [comment]
@akkamboj Yes we plan of update, i will be possible may 2020 (Flutter v2, Polyline)

**Comment by munkh-altai** [comment]
Version 2.0.3 exceededTransferLimit set to true ArcGIS rest API
